export const SET_USER_MENU_VISIBILITY = 'SET_USER_MENU_VISIBILITY';
export const SET_LOGIN_FORM_ACTIVE_STATUS = 'SET_LOGIN_FORM_ACTIVE_STATUS';
export const SHOW_SYSTEM_MESSAGE = 'SHOW_SYSTEM_MESSAGE';
export const HIDE_SYSTEM_MESSAGE = 'HIDE_SYSTEM_MESSAGE';

export const FETCH_DEPARTMENTS_PENDING = 'FETCH_DEPARTMENTS_PENDING';
export const FETCH_DEPARTMENTS_FULFILLED = 'FETCH_DEPARTMENTS_FULFILLED';
export const FETCH_DEPARTMENTS_REJECTED = 'FETCH_DEPARTMENTS_REJECTED';

export const FETCH_INITIAL_DATA_PENDING = 'FETCH_INITIAL_DATA_PENDING';
export const FETCH_INITIAL_DATA_FULFILLED = 'FETCH_INITIAL_DATA_FULFILLED';
export const FETCH_INITIAL_DATA_REJECTED = 'FETCH_INITIAL_DATA_REJECTED';